name = "kanshichao"
license = "GNU General Public License v3.0"
licenselink = "https://github.com/kanshichao/blob/master/LICENSE"
description = "A gorgeous responsive theme for Hugo blog framework"
homepage = "https://github.com/kanshichao"
tags = ["blog", "minimal", "responsive", "personal", "customizable", "creative", "fontawesome", "highlight.js"]
features = ["blog", "themes", "disqus", "minimal", "responsive", "font awesome", "highlight.js"]
min_version = 0.53

[author]
  name = "Shichao Kan"
  homepage = "https:kanshichao.github.io"
 
