
sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/kanshichao
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    on:
        branch: master
    local_dir: public
    repo: kanshichao/kanshichao.github.io
    target_branch: master
    email: kanshichao10281078@126.com
    name: kanshichao
